# Generated by Django 2.2 on 2019-04-19 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherlist',
            old_name='smile',
            new_name='mood',
        ),
        migrations.RenameField(
            model_name='weatherlist',
            old_name='coment',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='weatherlist',
            old_name='zaryadka',
            new_name='training',
        ),
    ]
